### PR TITLE
Fix invalid object usage for connect request

### PR DESCRIPTION
**Pull request by ErwinSteffens**
Fix invalid object usage for connect request

### CODE REVIEW

**Comment by ErwinSteffens** [comment]
Can you bump the version number? ;-)

**Comment by dufourgilles** [comment]
Done.
Thanks for all the work !!!

**Comment by ErwinSteffens** [comment]
No problem!

Are you sure you did a compile before pushing the package?

**Comment by dufourgilles** [comment]
Looks like not.
Did it again.

G.

**Pull request merged**
